title: "gafish's blog"
baseurl: "http://gafish.code.so/"
theme: "hugo-rapid-theme"
copyright: "Copyright (c) 2021. All rights reserved."
params:
  CopyrightHTML: "Copyright &#xA9; 2021. All Rights Reserved."
  GitHubUser: "coderzh"
  SidebarRecentLimit: 5
  # DateForm : "2021年09月26日"
  Tagline: "/** 编程、读书、资源分享 **/"
  Description: "如果你没有感觉到时间不够用时，你多半正在虚度光阴。"
  Keywords: "技术博客,程序员,读书思考,技术分享"
  Categories:
    - "原创教程"
    - "编程开发"
    - "思考感悟"
    - "精品软件"
    - "资源分享"
menu:
  main:
      - Name: "归档"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
      - Name: "关于我"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "about"
        Weight: -100
        URL: "/about/"
      - Name: "实用工具"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "tools"
        Weight: -100
        URL: "/tools/"
author:
  name: "gafish"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
  
markup:
  goldmark:
    renderer:
      unsafe: true